[2022-12-17T14:40:40.356+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: currency_daily.Daily_Currency_Avg scheduled__2022-12-16T00:00:00+00:00 [queued]>
[2022-12-17T14:40:40.430+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: currency_daily.Daily_Currency_Avg scheduled__2022-12-16T00:00:00+00:00 [queued]>
[2022-12-17T14:40:40.431+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:40:40.436+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-17T14:40:40.437+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:40:40.535+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): Daily_Currency_Avg> on 2022-12-16 00:00:00+00:00
[2022-12-17T14:40:40.550+0000] {standard_task_runner.py:55} INFO - Started process 2629 to run task
[2022-12-17T14:40:40.562+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'currency_daily', 'Daily_Currency_Avg', 'scheduled__2022-12-16T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_currency_daily.py', '--cfg-path', '/tmp/tmpy7iqikqd']
[2022-12-17T14:40:40.567+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask Daily_Currency_Avg
[2022-12-17T14:40:40.806+0000] {task_command.py:376} INFO - Running <TaskInstance: currency_daily.Daily_Currency_Avg scheduled__2022-12-16T00:00:00+00:00 [running]> on host dc5e6801fe25
[2022-12-17T14:40:40.971+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=handoyo
AIRFLOW_CTX_DAG_ID=currency_daily
AIRFLOW_CTX_TASK_ID=Daily_Currency_Avg
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-16T00:00:00+00:00
[2022-12-17T14:40:40.976+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-17T14:40:40.978+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/fact_currency_daily_avg.py']
[2022-12-17T14:40:41.008+0000] {subprocess.py:86} INFO - Output:
[2022-12-17T14:40:41.295+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/dags/fact_currency_daily_avg.py': [Errno 2] No such file or directory
[2022-12-17T14:40:41.302+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-12-17T14:40:41.324+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-17T14:40:41.331+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=currency_daily, task_id=Daily_Currency_Avg, execution_date=20221216T000000, start_date=20221217T144040, end_date=20221217T144041
[2022-12-17T14:40:41.364+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 9 for task Daily_Currency_Avg (Bash command failed. The command returned a non-zero exit code 2.; 2629)
[2022-12-17T14:40:41.399+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T14:40:41.461+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
